/*  =========================================================================
    aisnmea - generated layer of public API

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AISNMEA_LIBRARY_H_INCLUDED
#define AISNMEA_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  AISNMEA version macros for compile-time API detection
#define AISNMEA_VERSION_MAJOR 1
#define AISNMEA_VERSION_MINOR 0
#define AISNMEA_VERSION_PATCH 0

#define AISNMEA_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AISNMEA_VERSION \
    AISNMEA_MAKE_VERSION(AISNMEA_VERSION_MAJOR, AISNMEA_VERSION_MINOR, AISNMEA_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined AISNMEA_STATIC
#       define AISNMEA_EXPORT
#   elif defined AISNMEA_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define AISNMEA_EXPORT __declspec(dllexport)
#       else
#           define AISNMEA_EXPORT
#       endif
#   elif defined AISNMEA_EXPORTS
#       define AISNMEA_EXPORT __declspec(dllexport)
#   else
#       define AISNMEA_EXPORT __declspec(dllimport)
#   endif
#   define AISNMEA_PRIVATE
#else
#   define AISNMEA_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define AISNMEA_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define AISNMEA_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  AISNMEA_BUILD_DRAFT_API
#define AISNMEA_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef AISNMEA_BUILD_DRAFT_API
typedef struct _aisnmea_t aisnmea_t;
#define AISNMEA_T_DEFINED
#endif // AISNMEA_BUILD_DRAFT_API


//  Public classes, each with its own header file

#ifdef AISNMEA_BUILD_DRAFT_API
//  Self test for private classes
AISNMEA_EXPORT void
    aisnmea_private_selftest (bool verbose);
#endif // AISNMEA_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
